#!/usr/bin/env python3

"""
Script to check the weather in Spain from "https://www.eltiempo.es".

The way to call this script is by:

    "python weather2.py"

The location that will be used to call the page must be specified in a
location.py file in this directory (not in the repo) as:

    LOCATION = "location"

Then the request will be send to the page:

    "https://www.eltiempo.es/LOCATION.html"

If the page has no info for the input location it will do nothing, otherwise
it will print the temperature and the cloud state with icons.
"""

import sys
import requests
import bs4
from location import LOCATION


CLOUD_CORRESPONDENCE = {
    'mostly-clear' : '',
    'cloudless' : '',
    'partly-cloudy' : '杖',
    'overcast-light-rain' : '殺',
    'overcast' : '',
    'night-partly-cloudy' : '',
}


def extract_info(content):
    """
    Extracts the information from a typical weather page.
    """
    content = bs4.BeautifulSoup(content, 'lxml')
    info = content.select_one('#topHeader').select('.m_tables_top_temp')[0]
    temp = info.select_one('span').attrs['data-temp']
    cloud = info.select_one('i').attrs['class']
    cloud.remove('icon_weather_xl')
    cloud = cloud[0]
    cloud_icon = CLOUD_CORRESPONDENCE.get(cloud, cloud)
    return f'{cloud_icon}  {temp}C\n'


url = f'https://www.eltiempo.es/{LOCATION}.html'

ses = requests.session()

content = ses.get(url)

if content.ok:
    print(extract_info(content.content))
else:
    print('')
